public interface MusicDataProducer : Object {
    public abstract ServiceResponse? register_song_history(int song_id) throws OnnojiError;
    public abstract ServiceResponse? query_song_stream(int song_id) throws OnnojiError;
    public abstract ServiceResponse? query_artwork_default() throws OnnojiError;
    public abstract ServiceResponse? query_artwork(int artwork_id) throws OnnojiError;
    public abstract ServiceResponse? query_song_artwork(int song_id) throws OnnojiError;
    public abstract ServiceResponse? query_song_genres(int song_id) throws OnnojiError;
    public abstract ServiceResponse? query_song_artists(int song_id) throws OnnojiError;
    public abstract ServiceResponse? query_song_albums(int song_id) throws OnnojiError;
    public abstract ServiceResponse? query_song_playlists(int song_id) throws OnnojiError;
    public abstract ServiceResponse? query_song_metadata(int song_id) throws OnnojiError;
    public abstract ServiceResponse? query_playlist_by_id(int playlist_id) throws OnnojiError;
    public abstract ServiceResponse? query_playlist_songs(int playlist_id) throws OnnojiError;
    public abstract ServiceResponse? query_playlist_genres(int playlist_id) throws OnnojiError;
    public abstract ServiceResponse? query_playlist_artists(int playlist_id) throws OnnojiError;
    public abstract ServiceResponse? query_playlist_artworks(int playlist_id) throws OnnojiError;
    public abstract ServiceResponse? query_playlist_artwork(int playlist_id) throws OnnojiError;
    public abstract ServiceResponse? query_genre_songs(int genre_id) throws OnnojiError;
    public abstract ServiceResponse? register_genre_icon(int genre_id, string genre_icon_file_path) throws OnnojiError;
    public abstract ServiceResponse? query_genre_icon(int genre_id) throws OnnojiError;
    public abstract ServiceResponse? query_genre_playlists(int genre_id) throws OnnojiError;
    public abstract ServiceResponse? query_genre_albums(int genre_id) throws OnnojiError;
    public abstract ServiceResponse? query_genre_artists(int genre_id) throws OnnojiError;
    public abstract ServiceResponse? query_artist(int artist_id) throws OnnojiError;
    public abstract ServiceResponse? query_artist_songs(int artist_id) throws OnnojiError;
    public abstract ServiceResponse? query_artist_playlists(int artist_id) throws OnnojiError;
    public abstract ServiceResponse? query_artist_albums(int artist_id) throws OnnojiError;
    public abstract ServiceResponse? query_artist_genres(int artist_id) throws OnnojiError;
    public abstract ServiceResponse? query_recently_requested_playlists(int min, int max, bool is_album) throws OnnojiError;
    public abstract ServiceResponse? query_recently_requested_songs(int min, int max) throws OnnojiError;
    public abstract ServiceResponse? query_recently_registered_playlists(int min, int max, bool is_album) throws OnnojiError;
    public abstract ServiceResponse? query_recently_registered_songs(int min, int max) throws OnnojiError;
    public abstract ServiceResponse? query_artists() throws OnnojiError;
    public abstract ServiceResponse? query_genres() throws OnnojiError;
    public abstract ServiceResponse? register_playlist_with_songs(string playlist_name, Gee.List<PostFileData> file_list) throws OnnojiError;
}
